version: "3.8"
services:
    app-builder:
        build:
            context: packages
            target: builder
        image: app-builder:latest
    app:
        build:
            context: packages
            target: app
        image: app:latest
